name: st
channels:
  - conda-forge
  - nvidia
  - pytorch
  - defaults

dependencies:
  - python=3.9
  - impi-devel
  - pip  

  - pip:
    - brotli==1.1.0
    - cffi==1.17.1
    - colorama==0.4.6
    - conda-libmamba-solver==25.4.0
    - h2==4.2.0
    - ipykernel==6.29.5
    - jaraco.collections==5.1.0
    - libmambapy==2.3.1
    - pysocks==1.7.1
    - seaborn==0.13.2
    - tomli==2.0.1
    - torchaudio==2.7.0
    - torchsisso==0.1.8
    - torchvision==0.22.0
